homework1.5massive
anosov34/homework1.1 pull request #5
Opened 2021-09-15 18:04 UTC by anosov34

Массивы - оч сложно и массивно=)

2021-09-17 13:25 UTC, DisterRU requested changes
По 4 и 5 нет вопросов. 
По логике работы первых трех тоже.
Но вот по внедрению кода в метод генерации массива есть большой вопрос и его нужно решить.
Так же не требуется возвращать массив в качестве результата из первых трех методов.

2021-09-17 13:25 UTC, DisterRU commented on src/pro/sky/java/course1/lesson5/Homework5Massive.java
> +        int[] task3 = generateRandomArray3();
Это что-то прямо очень странное.
Код на генерацию, который был дан в дз, нужно было вызывать в своем методе при инициализации массива.
Ты же зачем-то начал код писать прямо в этом методе.
Не надо так.

2021-09-17 13:25 UTC, DisterRU commented on src/pro/sky/java/course1/lesson5/Homework5Massive.java
> +        int minArr = 201_000;
Массив arr должен был быть инициализирован с помощью вызова метода generateRandomArray().
Обе переменные стоило инициализировать arr[0], но в твоем случае массив ещё не заполнен, потому корректно, но массив должен был быть заполнен.

2021-09-17 13:25 UTC, DisterRU commented on src/pro/sky/java/course1/lesson5/Homework5Massive.java
> +            arr[index] = random.nextInt(100_000) + 100_000;
Эти 3 строки стираем и осуществляем вычисление минимума и максимума в одном цикле.

2021-09-17 13:25 UTC, DisterRU commented on src/pro/sky/java/course1/lesson5/Homework5Massive.java
> +            arr[index] = random.nextInt(100_000) + 100_000;
Зачем ты перезаполняешь массив во втором цикле?

2021-09-17 13:25 UTC, DisterRU commented on src/pro/sky/java/course1/lesson5/Homework5Massive.java
> +            sum = sum + arr[i];
В первом методе корректно использовал +=, а здесь забыл.

2021-09-17 13:25 UTC, DisterRU commented on src/pro/sky/java/course1/lesson5/Homework5Massive.java
> +        return arr;
А возвращать зачем?

2021-09-17 13:25 UTC, DisterRU commented on src/pro/sky/java/course1/lesson5/Homework5Massive.java
> +        }
Для печати стоило взять код из описания ДЗ.
Цикл for в целом здесь требует замен на foreach.

2021-09-18 07:03 UTC, anosov34 commented on src/pro/sky/java/course1/lesson5/Homework5Massive.java
> +        return arr;
Скажу честно - не знаю. Я вообще понятия не имел как работает этот метод, использовал его только потому, что так было написано в ДЗ=) 
Как-то я его удалил и система мне написала, что он нужен, поэтому и перестал его трогать от греха подальше

2021-09-18 07:08 UTC, anosov34 commented on src/pro/sky/java/course1/lesson5/Homework5Massive.java
> +        return arr;
`     sum += arr[i];
        }
        System.out.println("Средняя сумма трат за месяц составила " +  sum / arr.length + " рублей");
//        return arr; `

Закомментил ретёрн и не система перестаёт работать. Выдаёт: java: missing return statement

2021-09-20 13:03 UTC, DisterRU commented on src/pro/sky/java/course1/lesson5/Homework5Massive.java
> +            arr[index] = random.nextInt(100_000) + 100_000;
Эти строки всё ещё некорректны. Их нужно убирать.

2021-09-20 13:03 UTC, DisterRU commented on src/pro/sky/java/course1/lesson5/Homework5Massive.java
> +        java.util.Random random = new java.util.Random();
Эти строки всё ещё некорректны. Их нужно убирать.

2021-09-20 13:03 UTC, DisterRU commented on src/pro/sky/java/course1/lesson5/Homework5Massive.java
> +            arr[i] = random.nextInt(100_000) + 100_000;
Эти строки всё ещё некорректны. Их нужно убирать.

2021-09-20 13:04 UTC, DisterRU commented on src/pro/sky/java/course1/lesson5/Homework5Massive.java
> +            arr[index] = random.nextInt(100_000) + 100_000;
Строки всё ещё не убраны.

2021-09-21 05:10 UTC, anosov34 commented on src/pro/sky/java/course1/lesson5/Homework5Massive.java
> +        }
Вот этот твой коммент, кажется, единственное, что я не исправил. Эту задачу мы разбирали с Даниилом на созвоне и я просто не понимаю как её делать по-другому, а не так, как он объяснял.

2021-09-23 10:30 UTC, DisterRU approved these changes
Поправь по комментариям и можно мержить.

2021-09-23 10:30 UTC, DisterRU commented on src/pro/sky/java/course1/lesson5/Homework5Massive.java
> +        int maxArr = 0;
Тоже можно expenses[0] присвоить.

2021-09-23 10:30 UTC, DisterRU commented on src/pro/sky/java/course1/lesson5/Homework5Massive.java
> +        double summary = sum;
Лишняя переменная.
Если нужно закастить в double, достаточно просто указать (double) перед переменной.
Например, в выражении ниже написать (double) sum / arr.length

2021-09-23 10:30 UTC, DisterRU commented on src/pro/sky/java/course1/lesson5/Homework5Massive.java
> +        }
Задача сделана правильно.
Просто печатать матрицу следует тем образом, что указан на странице дз в качестве подсказки.

2021-10-03 12:15 UTC, merged